
services:
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowbit
      - JWT_SECRET=supersecretkey
      - WEBHOOK_SECRET=flowbit-webhook-secret
    volumes:
      - ./api:/app
    depends_on:
      - mongo

  frontend-shell:
    build: ./frontend-shell
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API=http://localhost:5000
    depends_on:
      - api

  support-tickets:
    build: ./support-tickets
    ports:
      - '3001:3001'
    depends_on:
      - api

  n8n:
    image: n8nio/n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n-data:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok:latest
    command: http n8n:5678
    environment:
      NGROK_AUTHTOKEN: 2zy4V0wI0FSewQpO1VHyBAuNFZh_6fvQb3CGgJRf7kKPPsjrx
    ports:
      - '4040:4040'

volumes:
  mongo-data:
  n8n-data:
